2021-11-18 10:22:19,536 -Loc multi_threaded_logger.py -Pid 12931 -root -ERROR - test error log0
2021-11-18 10:22:21,551 -Loc multi_threaded_logger.py -Pid 12932 -root -ERROR - test error log2
2021-11-18 10:22:21,551 -Loc multi_threaded_logger.py -Pid 12931 -root -ERROR - test error log3
2021-11-18 10:22:23,565 -Loc multi_threaded_logger.py -Pid 12932 -root -ERROR - test error log4
2021-11-18 10:22:23,565 -Loc multi_threaded_logger.py -Pid 12931 -root -ERROR - test error log5
2021-11-18 10:22:25,580 -Loc multi_threaded_logger.py -Pid 12932 -root -ERROR - test error log6
2021-11-18 10:22:25,580 -Loc multi_threaded_logger.py -Pid 12931 -root -ERROR - test error log7
2021-11-18 10:22:27,596 -Loc multi_threaded_logger.py -Pid 12931 -root -ERROR - test error log9
2021-11-18 10:22:27,596 -Loc multi_threaded_logger.py -Pid 12932 -root -ERROR - test error log8
