2021-11-18 10:21:56,058 -Loc multi_threaded_logger.py -Pid 12913 -root -ERROR - test error log0
2021-11-18 10:21:56,061 -Loc multi_threaded_logger.py -Pid 12914 -root -ERROR - test error log1
2021-11-18 10:21:58,073 -Loc multi_threaded_logger.py -Pid 12913 -root -ERROR - test error log2
2021-11-18 10:21:58,074 -Loc multi_threaded_logger.py -Pid 12914 -root -ERROR - test error log3
2021-11-18 10:22:00,088 -Loc multi_threaded_logger.py -Pid 12914 -root -ERROR - test error log5
2021-11-18 10:22:00,088 -Loc multi_threaded_logger.py -Pid 12913 -root -ERROR - test error log4
2021-11-18 10:22:02,099 -Loc multi_threaded_logger.py -Pid 12913 -root -ERROR - test error log7
2021-11-18 10:22:02,099 -Loc multi_threaded_logger.py -Pid 12914 -root -ERROR - test error log6
2021-11-18 10:22:04,111 -Loc multi_threaded_logger.py -Pid 12914 -root -ERROR - test error log9
2021-11-18 10:22:04,111 -Loc multi_threaded_logger.py -Pid 12913 -root -ERROR - test error log8
2021-11-18 10:22:19,536 -Loc multi_threaded_logger.py -Pid 12932 -root -ERROR - test error log1
